### ISSUE TITLE
SÍNTESIS: WEBINAR GRATUITO "BUENAS PRÁCTICAS EN  GESTIÓN DE PROYECTOS" 

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/sintesis-Eva155#2]
[SÍNTESIS_WEBINAR GRATUITO_BUENAS PRÁCTICAS EN GESTIÓN DE PROYECTOS.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Eva155/files/7119871/SINTESIS_WEBINAR.GRATUITO_BUENAS.PRACTICAS.EN.GESTION.DE.PROYECTOS.pdf)

**Comment by dulce-blm** [comment]
Calificación 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
